package com.maxtauro.airdroidcommon


// TODO rename/clean dis shit up
const val WEARABLE_DATA_AIRPOD_STATUS_PATH = "/airpodStatusRequest"

const val WEARABLE_DATA_AIRPOD_NAME = "WEARABLE_DATA_AIRPOD_NAME"

const val WEARABLE_DATA_LEFT_CHARGE_LEVEL = "LEFT_CHARGE_LEVEL"
const val WEARABLE_DATA_RIGHT_CHARGE_LEVEL = "RIGHT_CHARGE_LEVEL"
const val WEARABLE_DATA_CASE_CHARGE_LEVEL = "CASE_CHARGE_LEVEL"

const val WEARABLE_DATA_LEFT_CHARGE_STATE = "LEFT_CHARGE_STATE"
const val WEARABLE_DATA_RIGHT_CHARGE_STATE = "RIGHT_CHARGE_STATE"
const val WEARABLE_DATA_CASE_CHARGE_STATE = "CASE_CHARGE_STATE"